default:
  host: <%= ENV.fetch("REDIS_HOST") { "localhost" } %>
  port: <%= ENV.fetch("REDIS_PORT") { 6379 } %>
development:
  db: <%= ENV.fetch("REDIS_DB") { 0 } %>
test:
  db: 1
production:
  db: <%= ENV["REDIS_DB"] %>
  host: <%= ENV["REDIS_HOST"] %>
